import React from 'react'

// NEXT
import Head from 'next/head'
import { Button, Typography } from '@mui/material'
import { useDispatch, useSelector } from 'react-redux'
import { selectUserState, setDataState } from '@/store/slice/userSlice'

export default function Home() {
  const userState = useSelector(selectUserState)
  const dispatch = useDispatch()
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <Typography variant='h1'>{userState?.data?.login ? 'loged in' : 'loged out'}</Typography>

      <Button onClick={() => dispatch(setDataState({ login: true }))} variant='outlined'>login</Button>
    </>
  )
}
