import React from 'react'

// NEXT
import Head from 'next/head'
import { Button, Typography } from '@mui/material'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <Typography variant='h1'>test judul</Typography>

      <Button variant='outlined'>test</Button>
    </>
  )
}
