name: linting and unit testing
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          fetch-depth: 0
          node-version: ${{ matrix.node-version }}
      - name: install and build
        run: |
          npm install conventional-changelog-conventionalcommits
          npm install commitlint@latest
          npm ci
          npm run build --if-present

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: npx commitlint --from HEAD~1 --to HEAD --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: lint
        run: npm run lint

      - name: unit and integration testing
        run: npm run test-unit
